name: CI Jupyter LAB
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, 'jupyter') || github.event_name == 'workflow_dispatch'"
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: |
        docker build --file Dockerfiles/Dockerfile2 -t dorianalp38/jupyter-ai:latest ..
    - name: Push the tagged Docker image
      run: |
        d=$(date +%Y-%m-%d--%H-%M-%S)
        docker tag dorianalp38/Jupyter-AI:latest dorianalp38/Jupyter-AI:$d
        docker push dorianalp38/Jupyter-AI:$d
        docker push dorianalp38/Jupyter-AI:latest
