name: CI Jupyter LAB
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, 'jupyter') || github.event_name == 'workflow_dispatch'"
    steps:
    - uses: actions/checkout@v2
    - name: Connexion au registre DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Construire l'image Docker
      working-directory: .
      run: docker build --file Dockerfiles/Dockerfile2 --tag dorianalp38/jupyter-ai:latest .  
    - name: Pousser l'image Docker taguée
      run: |
          d=$(date +%Y-%m-%d--%H-%M-%S)
          docker tag dorianalp38/jupyter-ai:latest dorianalp38/jupyter-ai:$d
          docker push dorianalp38/jupyter-ai:$d
          docker push dorianalp38/jupyter-ai:latest
